```{r predtf, fig.cap="Predictors of transferrin/ferritin measure", cache=cacheon}

modvars_tfpred <- c(modvars_tf[!modvars_tf %in% c("shf_indexmonth")], "shf_indexyear")

ormod <- with(imp_tf, glm(formula(paste0("shf_tf2 == 'Yes' ~ ", paste(modvars_tfpred, collapse = " + "))),
  family = binomial(link = "logit")
))

sormod <- summary(pool(ormod))

nval <- length(sormod$term)
orforest <- bind_cols(
  var = as.character(sormod$term[2:nval]),
  logor = sormod$estimate[2:nval],
  lci = sormod$estimate[2:nval] - global_z05 * sormod$std.error[2:nval],
  uci = sormod$estimate[2:nval] + global_z05 * sormod$std.error[2:nval],
  p = dF(sormod$p.value[2:nval], dig = 3, p = TRUE)
)

orforest <- orforest %>%
  # remove = Yes
  mutate(across(everything(), str_replace_all, fixed("Yes"), "")) %>%
  # to get labs and units in place
  mutate(
    # if recoding or categorizing will still get org label
    var_tmp = str_replace_all(var, "(_cat2|_cat)", ""),
    # if shf/sos combination  will still get org label
    var_tmp = str_replace_all(var_tmp, "shf_sos_com_", "sos_com_"),
  )

orforest <- left_join(orforest,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("var_tmp" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var_tmp),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    )
  )

orforest <- orforest %>%
  mutate(
    modnameforest = case_when(
      Variable == "shf_nyhaIV" ~ "NYHA IV vs I",
      Variable == "shf_nyhaIII" ~ "NYHA III vs I",
      Variable == "shf_nyhaII" ~ "NYHA II vs I",
      Variable == "shf_anemia" ~ "Anemia",
      Variable %in% c("shf_ntpropbnpAbove medium within EF", "shf_ntpropbnpAbove medium") ~ "NTproBNP Above vs below medium",
      Variable == "shf_potassiumhypokalemia" ~ "Hypokalemia",
      Variable == "scb_famtypeLiving alone" ~ "Living alone",
      Variable == "shf_deviceCRT/ICD" ~ "CRT/ICD",
      Variable == "shf_durationhf>6mo" ~ "Duration HF > 6mo",
      Variable == "shf_age>=75" ~ "Age>=75 vs <75",
      Variable == "shf_potassiumhyperkalemia" ~ "Hyperkalemia",
      Variable == "shf_smokingFormer/Current" ~ "Former/Current smoker",
      Variable == "scb_educationUniversity" ~ "University vs Compulsory school",
      Variable == "scb_educationSecondary school" ~ "Secondary vs Compulsory school",
      Variable == "shf_bmi>=30" ~ "BMI>=30 vs <30",
      Variable == "shf_followuplocationOther" ~ "Follow-up Other vs Hospital",
      Variable == "shf_followuplocationPrimary care" ~ "Follow-up Primary care vs Hospital",
      Variable == "shf_efHFmrEF" ~ "HFmrEF vs HFrEF",
      Variable == "shf_sexMale" ~ "Male vs Female",
      Variable == "shf_efHFpEF" ~ "HFpEF vs HFrEF",
      Variable == "scb_dispincomeAbove medium" ~ "Income Above vs below medium",
      Variable == "shf_map>90" ~ "MAP>90 vs <=90",
      Variable == "shf_gfrckdepi<60" ~ "eGFR<60 vs >=60",
      Variable == "shf_heartrate>70" ~ "Heart rate>70 vs <=70",
      Variable == "shf_locationOut-patient" ~ "Out vs In-patient",
      Variable == "shf_indexyear2018" ~ "Year of inclusion 2018 vs 2017",
      TRUE ~ Variable
    ),
    logor = as.numeric(logor)
  ) %>%
  arrange(logor)

# exp(min(as.numeric(orforest$lci)))
# exp(max(as.numeric(orforest$uci)))

cextext <- 0.5

# c(bottom, left, top, right)
par(mar = c(4, 8, 1, 4) + 0.2)
plot(orforest$logor, 1:nrow(orforest),
  xlab = "",
  xlim = c(
    log(0.6),
    log(3.5)
  ),
  ylim = c(1, nrow(orforest) + 1),
  axes = FALSE,
  ylab = NA,
  cex.lab = 1.1,
  main = NA,
  cex = 1,
  type = "p",
  pch = 22,
  bg = global_kicols[1],
  col = global_kicols[1]
)


for (i in 1:nrow(orforest)) {
  matplot(c(orforest$lci[i], orforest$uci[i]), c(i, i),
    type = "l", add = TRUE, col = global_kicols[1], cex = 2
  )
}

matplot(c(0, 0), c(-1, nrow(orforest) + 0.5), type = "l", lty = 3, add = TRUE, col = "black")

axis(1,
  cex.axis = cextext, at = log(c(seq(0.6, 1, 0.1), seq(1.5, 3.5, 0.5))),
  labels = c(0.6, 0.7, 0.8, 0.9, 1.0, 1.5, 2, 2.5, 3, 3.5)
)

axis(2,
  at = 1:(nrow(orforest) + 1),
  labels = c(orforest$modnameforest, "Variable"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 7, hadj = 0
)

axis(2,
  at = 1:(nrow(orforest) + 1),
  labels = c(orforest$p, "P-value"),
  cex.axis = cextext, tick = FALSE, las = 2, line = -25, hadj = 0.5
)

axis(1,
  at = 0.01, cex.axis = cextext,
  labels = "Measure less likely         Measure more likely", line = 1, tick = FALSE
)
```

```{r predtfhb, fig.cap="Predictors of transferrin/ferritin measure (HB categories replacing anemia)", cache=cacheon}

modvars_tfpred <- c(modvars_tf[!modvars_tf %in% c("shf_indexmonth", "shf_anemia")], "shf_indexyear", "shf_hb_cat")

ormod <- with(imp_tfhb, glm(formula(paste0("shf_tf2 == 'Yes' ~ ", paste(modvars_tfpred, collapse = " + "))),
  family = binomial(link = "logit")
))

sormod <- summary(pool(ormod))

nval <- length(sormod$term)
orforest <- bind_cols(
  var = as.character(sormod$term[2:nval]),
  logor = sormod$estimate[2:nval],
  lci = sormod$estimate[2:nval] - global_z05 * sormod$std.error[2:nval],
  uci = sormod$estimate[2:nval] + global_z05 * sormod$std.error[2:nval],
  p = dF(sormod$p.value[2:nval], dig = 3, p = TRUE)
)

orforest <- orforest %>%
  # remove = Yes
  mutate(across(everything(), str_replace_all, fixed("Yes"), "")) %>%
  # to get labs and units in place
  mutate(
    # if recoding or categorizing will still get org label
    var_tmp = str_replace_all(var, "(_cat2|_cat)", ""),
    # if shf/sos combination  will still get org label
    var_tmp = str_replace_all(var_tmp, "shf_sos_com_", "sos_com_"),
  )

orforest <- left_join(orforest,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("var_tmp" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var_tmp),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    )
  )

orforest <- orforest %>%
  mutate(
    modnameforest = case_when(
      Variable == "shf_nyhaIV" ~ "NYHA IV vs I",
      Variable == "shf_nyhaIII" ~ "NYHA III vs I",
      Variable == "shf_nyhaII" ~ "NYHA II vs I",
      Variable == "shf_anemia" ~ "Anemia",
      Variable %in% c("shf_ntpropbnpAbove medium within EF", "shf_ntpropbnpAbove medium") ~ "NTproBNP Above vs below medium",
      Variable == "shf_potassiumhypokalemia" ~ "Hypokalemia",
      Variable == "scb_famtypeLiving alone" ~ "Living alone",
      Variable == "shf_deviceCRT/ICD" ~ "CRT/ICD",
      Variable == "shf_durationhf>6mo" ~ "Duration HF > 6mo",
      Variable == "shf_age>=75" ~ "Age>=75 vs <75",
      Variable == "shf_potassiumhyperkalemia" ~ "Hyperkalemia",
      Variable == "shf_smokingFormer/Current" ~ "Former/Current smoker",
      Variable == "scb_educationUniversity" ~ "University vs Compulsory school",
      Variable == "scb_educationSecondary school" ~ "Secondary vs Compulsory school",
      Variable == "shf_bmi>=30" ~ "BMI>=30 vs <30",
      Variable == "shf_followuplocationOther" ~ "Follow-up Other vs Hospital",
      Variable == "shf_followuplocationPrimary care" ~ "Follow-up Primary care vs Hospital",
      Variable == "shf_efHFmrEF" ~ "HFmrEF vs HFrEF",
      Variable == "shf_sexMale" ~ "Male vs Female",
      Variable == "shf_efHFpEF" ~ "HFpEF vs HFrEF",
      Variable == "scb_dispincomeAbove medium" ~ "Income Above vs below medium",
      Variable == "shf_map>90" ~ "MAP>90 vs <=90",
      Variable == "shf_gfrckdepi<60" ~ "eGFR<60 vs >=60",
      Variable == "shf_heartrate>70" ~ "Heart rate>70 vs <=70",
      Variable == "shf_locationOut-patient" ~ "Out vs In-patient",
      Variable == "shf_indexyear2018" ~ "Year of inclusion 2018 vs 2017",
      Variable == "shf_hb110-119" ~ "HB 110-119 vs <110",
      Variable == "shf_hb120-129" ~ "HB 120-129 vs <110",
      Variable == "shf_hb130-139" ~ "HB 130-139 vs <110",
      Variable == "shf_hb140-149" ~ "HB 140-149 vs <110",
      Variable == "shf_hb>=150" ~ "HB>=150 vs <110",
      TRUE ~ Variable
    ),
    logor = as.numeric(logor)
  ) %>%
  arrange(logor)

# exp(min(as.numeric(orforest$lci)))
# exp(max(as.numeric(orforest$uci)))

cextext <- 0.5

# c(bottom, left, top, right)
par(mar = c(4, 8, 1, 4) + 0.2)
plot(orforest$logor, 1:nrow(orforest),
  xlab = "",
  xlim = c(
    log(0.4),
    log(3.5)
  ),
  ylim = c(1, nrow(orforest) + 1),
  axes = FALSE,
  ylab = NA,
  cex.lab = 1.1,
  main = NA,
  cex = 1,
  type = "p",
  pch = 22,
  bg = global_kicols[1],
  col = global_kicols[1]
)


for (i in 1:nrow(orforest)) {
  matplot(c(orforest$lci[i], orforest$uci[i]), c(i, i),
    type = "l", add = TRUE, col = global_kicols[1], cex = 2
  )
}

matplot(c(0, 0), c(-1, nrow(orforest) + 0.5), type = "l", lty = 3, add = TRUE, col = "black")

axis(1,
  cex.axis = cextext, at = log(c(seq(0.4, 1, 0.1), seq(1.5, 3.5, 0.5))),
  labels = c(0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.5, 2, 2.5, 3, 3.5)
)

axis(2,
  at = 1:(nrow(orforest) + 1),
  labels = c(orforest$modnameforest, "Variable"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 7, hadj = 0
)

axis(2,
  at = 1:(nrow(orforest) + 1),
  labels = c(orforest$p, "P-value"),
  cex.axis = cextext, tick = FALSE, las = 2, line = -25, hadj = 0.5
)

axis(1,
  at = 0.01, cex.axis = cextext,
  labels = "Measure less likely         Measure more likely", line = 1, tick = FALSE
)
```