```{r tab1tf, cache=cacheon}

tab1 <- print(CreateTableOne(
  vars = tabvars,
  data = pdata_tf,
  strata = "shf_tf"
),
missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
catDigits = 1, contDigits = 1,
noSpaces = TRUE,
explain = FALSE
)

tab1 <- as_tibble(cbind(var = rownames(tab1), tab1)) %>%
  select(var, Missing, `Transferrin-/Ferritin-`:p)

tab1 <- tab1 %>%
  # remove = Yes
  mutate(across(everything(), str_replace_all, fixed(" = Yes"), "")) %>%
  # to get labs and units in place
  mutate(
    var_tmp = str_split(var, " = ", simplify = TRUE)[, 1],
    val_tmp = str_split(var, " = ", simplify = TRUE)[, 2],
    # if recoding or categorizing will still get org label
    var_tmp2 = str_replace_all(var_tmp, "(_cat2|_cat)", ""),
    # if shf/sos combination  will still get org label
    var_tmp2 = str_replace_all(var_tmp2, "shf_sos_com_", "sos_com_"),
  )

tab1 <- left_join(tab1,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("var_tmp2" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var_tmp),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    ),
    Variable = if_else(val_tmp != "",
      paste0(Variable, " ", val_tmp),
      Variable
    )
  )

write.xlsx(tab1 %>%
  select(Variable, Missing:p), paste0("./output/tabs/tab1_tf_", Sys.Date(), ".xlsx"), rowNames = FALSE)

# footnotes
tab1 <- tab1 %>%
  mutate(
    footnote1 = if_else(str_detect(var, "^shf_"), footnote_marker_symbol(1), ""),
    footnote2 = if_else(str_detect(var, "sos_"), footnote_marker_symbol(2), ""),
    footnote3 = if_else(str_detect(var, "^scb_"), footnote_marker_symbol(3), ""),
    footnote4 = if_else(var_tmp %in% c(modvars_tf, "shf_indexyear", "shf_hb_cat"), footnote_marker_symbol(4), ""),
    footnote5 = if_else(str_detect(var, "^shf_indexyear"), footnote_marker_symbol(5), ""),
    footnote6 = if_else(str_detect(var, "^shf_rasarni"), footnote_marker_symbol(6), ""),
    footnote7 = if_else(str_detect(var, "^scb_dispincome_cat"), footnote_marker_symbol(7), ""),
    footnote8 = if_else(str_detect(var, "^shf_ntpropbnp_cat"), footnote_marker_symbol(8), "")
  ) %>%
  unite(footnote, starts_with("footnote"), sep = "") %>%
  mutate(
    # so no probs
    Variable = sanitize_text(Variable),

    Variable = paste0(Variable, footnote),

    # space in Latex output (fix this other way?)
    Variable = sub("  ", ". ", Variable)
  ) %>%
  select(Variable, Missing:p)


## fix in order to use escape = TRUE
colnames(tab1) <- sanitize_text(c(
  "Variables", "Missing (%)", levels(pdata_tf$shf_tf), "p-value"
))

footnote(
  mykable(tab1,
    fontsize = 6,
    caption = "Baseline characteristics by recorded transferrin/ferritin measure",
    longtable = TRUE,
    escape = FALSE
  ) %>%
    landscape(),
  general = c(
    "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
  ),
  symbol = c(
    "Source: SwedeHF",
    "Source: NPR",
    "Source: SCB",
    "Included in the multiple imputation model (althought not necessarily imputed if there is no missing data) and logistic models, separate for shf_anemia and shf_hb_cat",
    "Included in the models as a continuous variable year and month",
    "arb/acei/arni",
    "Medium within index year",
    "Medium within EF"
  )
)
```

```{r tab1tf2, cache=cacheon}

tab1 <- print(CreateTableOne(
  vars = tabvars,
  data = pdata_tf,
  strata = "shf_tf2"
),
missing = TRUE, printToggle = FALSE, nonnormal = tabvars,
catDigits = 1, contDigits = 1,
noSpaces = TRUE,
explain = FALSE
)

tab1 <- as_tibble(cbind(var = rownames(tab1), tab1)) %>%
  select(var, Missing, No:p)

tab1 <- tab1 %>%
  # remove = Yes
  mutate(across(everything(), str_replace_all, fixed(" = Yes"), "")) %>%
  # to get labs and units in place
  mutate(
    var_tmp = str_split(var, " = ", simplify = TRUE)[, 1],
    val_tmp = str_split(var, " = ", simplify = TRUE)[, 2],
    # if recoding or categorizing will still get org label
    var_tmp2 = str_replace_all(var_tmp, "(_cat2|_cat)", ""),
    # if shf/sos combination  will still get org label
    var_tmp2 = str_replace_all(var_tmp2, "shf_sos_com_", "sos_com_"),
  )

tab1 <- left_join(tab1,
  meta.variables.Sheet.1 %>%
    select(variable, label, unit),
  by = c("var_tmp2" = "variable")
) %>%
  mutate(
    Variable = coalesce(label, var_tmp),
    Variable = if_else(!is.na(unit),
      paste0(Variable, " (", unit, ")"),
      Variable
    ),
    Variable = if_else(val_tmp != "",
      paste0(Variable, " ", val_tmp),
      Variable
    )
  )


write.xlsx(tab1 %>%
  select(Variable, Missing:p), paste0("./output/tabs/tab1_tf2_", Sys.Date(), ".xlsx"), rowNames = FALSE)

# footnotes
tab1 <- tab1 %>%
  mutate(
    footnote1 = if_else(str_detect(var, "^shf_"), footnote_marker_symbol(1), ""),
    footnote2 = if_else(str_detect(var, "sos_"), footnote_marker_symbol(2), ""),
    footnote3 = if_else(str_detect(var, "^scb_"), footnote_marker_symbol(3), ""),
    footnote4 = if_else(var_tmp %in% c(modvars_tf, "shf_indexyear", "shf_hb_cat"), footnote_marker_symbol(4), ""),
    footnote5 = if_else(str_detect(var, "^shf_indexyear"), footnote_marker_symbol(5), ""),
    footnote6 = if_else(str_detect(var, "^shf_rasarni"), footnote_marker_symbol(6), ""),
    footnote7 = if_else(str_detect(var, "^scb_dispincome_cat"), footnote_marker_symbol(7), ""),
    footnote8 = if_else(str_detect(var, "^shf_ntpropbnp_cat"), footnote_marker_symbol(8), "")
  ) %>%
  unite(footnote, starts_with("footnote"), sep = "") %>%
  mutate(
    # so no probs
    Variable = sanitize_text(Variable),

    Variable = paste0(Variable, footnote),

    # space in Latex output (fix this other way?)
    Variable = sub("  ", ". ", Variable)
  ) %>%
  select(Variable, Missing:p)


## fix in order to use escape = TRUE
colnames(tab1) <- sanitize_text(c(
  "Variables", "Missing (%)", levels(pdata_tf$shf_tf2), "p-value"
))

footnote(
  mykable(tab1,
    fontsize = 6,
    caption = "Baseline characteristics by recorded transferrin/ferritin measure - 2 groups",
    longtable = TRUE,
    escape = FALSE
  ) %>%
    landscape(),
  general = c(
    "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
  ),
  symbol = c(
    "Source: SwedeHF",
    "Source: NPR",
    "Source: SCB",
    "Included in the multiple imputation model (althought not necessarily imputed if there is no missing data) and logistic models, separate for shf_anemia and shf_hb_cat",
    "Included in the models as a continuous variable year and month",
    "arb/acei/arni",
    "Medium within index year",
    "Medium within EF"
  )
)
```
